version: "3.3"
services:
  shop-frontend:
    build: ./nextjs-frontend
    image: shop-frontend
    container_name: shop-frontend
    restart: unless-stopped
    ports:
      - 5003:3000
    environment:
      # DONT CHANGE HERE, CHANGE .env FILE INSIDE PROJECT
      # SINCE process.env is part of node, not the browser,
      # variables get accessed during build
      # - NEXT_PUBLIC_STRAPI_URL=<example.org>
      # - PLACEHOLDER_IMAGE_URL=<example.org>
      # - STRIPE_SECRET_KEY=<example>
      # - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=<example>
      - TZ=Europe/Madrid

  shop-strapi:
    container_name: shop-strapi
    image: public.ecr.aws/knowre/strapi:3.1.4-node12
    environment:
      NODE_ENV: production
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: shop-postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - $STRAPI_DATA:/srv/app
    ports:
      - "8007:1337"
    depends_on:
      - shop-postgres
    command: "strapi start"

  shop-postgres:
    container_name: shop-postgres
    user: "1001:0"
    image: public.ecr.aws/bitnami/postgresql:latest
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - $SHOP_POSTGRES_DATA:/bitnami/postgresql
        # shop-backend:
        # build: ./tienda-backend
        # image: shop-backend
        # container_name: shop-backend
        # restart: unless-stopped
        # ports:
        # - 8007:1337
        # environment:
        # - TZ=Europe/Madrid
